version: 2.1
orbs:
  matlab: mathworks/matlab@1.1.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - matlab/install:
          release: R2024a
          products: Deep Learning Toolbox
      - matlab/run-tests:
          test-results-junit: artifacts/test_results/matlab/results.xml
          # Have to add test/tools to the path for certain tests.
          source-folder: .;test/tools
      - store_test_results:
          path: artifacts/test_results
      - store_artifacts:
          path: artifacts/
